- Makefile
- README
- aula.cabal
- exec/RenderHtml.hs
- src/Api.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Html.hs
- src/Types.hs
stuck with a type puzzle.  it would be easy to take `MetaInfo` apart in the phantom-parameterized part and the one that carries access information, and that would solve my problem.  i just wonder if it also works like this.
> html vs. blaze

- .travis.yml
- aula.cabal
- tests/InitSpec.hs
- tests/Spec.hs
Initial commit to start testing with Hspec.
> Add Hspec and cabal test suite.

- aula.cabal
- exec/RenderHtml.hs
- src/Frontend.hs
- src/Frontend/Html.hs
- src/Types.hs
- tests/Api/PersistentSpec.hs
- tests/Frontend/HtmlSpec.hs
> Use lucid, not blaze

- README.md
- aula.cabal
- exec/RenderHtml.hs
- src/Api/Persistent.hs
- src/Arbitrary.hs
- src/Config.hs
- src/CreateRandom.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Html.hs
- src/Frontend/Page/CreateIdea.hs
- src/Frontend/Prelude.hs
- src/Persistent.hs
- src/Types.hs
- tests/Frontend/HtmlSpec.hs
> Create Idea Page refactor

- Makefile
- aula.cabal
- src/Frontend/Core.hs
- src/Frontend/Page/CreateIdea.hs
- tests/Frontend/HtmlSpec.hs
* New make command: `test-repl`
* `FormPageView` has an associated type and a new method to define forms
* Test suite, to check if the form renders and uses the same parameters as it was given in the view
> Test form rendering.

- aula.cabal
- exec/Aula.hs
- exec/ImportUsers.hs
- exec/RenderHtml.hs
- src/Arbitrary.hs
- src/Config.hs
- src/CreateRandom.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Html.hs
- src/Frontend/Page/CreateIdea.hs
- src/Frontend/Topics.hs
- src/Transaction.hs
- src/Types.hs
- tests/Api/PersistentSpec.hs
- tests/Frontend/HtmlSpec.hs
- tests/TypesSpec.hs
> 2016 02 15 np move topic page

- src/Frontend.hs
- src/Frontend/Html.hs
- src/Frontend/Page/Topics.hs
- src/Frontend/Prelude.hs
Please ignore the merge commits, I'll rebase of master when these will be merged.
> 2016 02 16 np create topics

- exec/RenderHtml.hs
- src/CreateRandom.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Topic.hs
Preparation, before merging Action monad. The username will come from the session.
> Add User as a Frame parameter.

- aula.cabal
- tests/AllModulesSpec.hs
(for exhaustive type checking in sensei.)
> Add specs module that imports src/**/*.hs

- src/Action.hs
- src/Api/Persistent.hs
Fixes #67.
(Some of this stuff I am inclined to call bug fixes.)
> Refine action abstraction

- src/Api/Persistent.hs
- src/Arbitrary.hs
- src/Frontend/Core.hs
- src/Frontend/Page/CreateIdea.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/Topic.hs
- src/Types.hs
- tests/Frontend/HtmlSpec.hs
This simply reflects the status so far.
Still need to be done:
* formRedirectH' needs to be moved to Servant.Missing, moreover we should decide if
it can replace formRedirectH.
* redirectFormHandler' should replace redirectFormHandler since the cost is only
to wrap pure pages with `pure`.
* split in smaller commits
* write tests
> Add ideas to topics

- aula.cabal
- src/Frontend.hs
- src/Frontend/Core.hs
> Handle missing trailing slashes in addresses

- README.md
A fix to docs. Pushing, in particular, to show how I'm invoking dummies and ask on IRC for help in debugging them.
> README.md Fix the instructions for dummies, etc.

- Makefile
- README.md
> Fix: sensei make rules; also add a little documentation.

- PageCreatorHOWTO.md
I will jot down the first draft before Wednesday. [edit: Feb 24th, to be precise]
> PageCreatorHOWTO.md: start writing the HOWTO

- .gitmodules
- src/Frontend/Core.hs
- static/third-party/Simple-Grid
(everything except the last space from @local-girl.  i just rebased.)
> 2016 02 cc html hack frame

- exec/RenderHtml.hs
better source comments based on comments to #104 by @np.  thanks!
> Fix readability of #104

- aula.cabal
- package.yaml
- src/Action.hs
- src/Frontend.hs
- tests/FrontendSpec.hs
Fixes #122.
Also related to #121, but nothing conclusive there yet.
This should be self-contained and ready for merge, for being picked up and finished later.
> Servant error handling

- src/Api/Persistent.hs
- src/CreateRandom.hs
- src/Frontend.hs
- src/Frontend/Page/Overview.hs
- src/Types.hs
- tests/Api/PersistentSpec.hs
- add some idea spaces to initial db
- make idea space overview clickable
> Improve idea space handling.

- aula.cabal
- src/Arbitrary.hs
- src/Data/UriPath.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Html.hs
- src/Frontend/Page.hs
- src/Frontend/Page/Delegation.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Prelude.hs
> First draft of delegation graph.

- src/Arbitrary.hs
- src/Frontend/Page/Admin.hs
- tests/Frontend/HtmlSpec.hs
- tests/Frontend/PathSpec.hs
fixes to prematurely merged #144
> Admin pages fixes

- aula.cabal
- package.yaml
- src/Arbitrary.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Path.hs
- src/Types.hs
During the development if we change the structure of our data, we had to adjust the arbitrary instances, which is kind of boilerplate. Usage of generics based arbitrary speeds up the development process.
> Generics based Arbitrary instances.

- exec/RenderHtml.hs
- src/Arbitrary.hs
> Finite garbitrary

- src/Arbitrary.hs
- src/Frontend/Core.hs
- src/Frontend/Page/FileUpload.hs
- src/Frontend/Page/Overview.hs
- src/Types.hs
This obsoletes #168.  I will take another shot at the `NFData` idea in a separate PR.  @Mikolaj, could you take a quick look if the haddocks for `redirectFormH` make sense now?  (Part of that text may look familiar.   :-)
> Bit and pieces

- aula.cabal
- src/Action.hs
- src/Api/Persistent.hs
- src/Api/PersistentImplementation.hs
- src/CreateRandom.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Delegation.hs
- src/Frontend/Page/FileUpload.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Persistent.hs
- src/Persistent/Api.hs
- src/Persistent/Implementation/STM.hs
- tests/AllModulesSpec.hs
- tests/Api/PersistentSpec.hs
- tests/Frontend/HtmlSpec.hs
- tests/FrontendSpec.hs
Please feel free to review and contribute while still in progress.
> Abstract over persistence implementation

- .travis.yml
- .travis/docker-build.sh
- aula.cabal
- package.yaml
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Path.hs
- stack.yaml
- tests/Frontend/PathSpec.hs
* Test suite for paths and handlers correspondence
* Travis runs 1000 test cases for every property
* New dependency on servant-mock
> Test path and handler correspondence

- Makefile
- exec/RenderHtml.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Path.hs
- src/Persistent/Api.hs
- src/Types.hs
- tests/Frontend/CoreSpec.hs
- tests/Persistent/ApiSpec.hs
This obsoletes #173.
Last commit breaks syntax and should be removed.
> Locations, spaces, topics of ideas.

- HLint.hs
- exec/RenderHtml.hs
- src/Arbitrary.hs
- src/Frontend/Page/Idea.hs
- src/Types.hs
This is mostly non-production code, plus a trivial fix in the `Timestamp` show/read instances that is covered by our test suite.
> Sample data etc

- Makefile
- do not touch package.yaml, aula.cabal.
- run ghc with -O0.
- run test suite, haddock.
> Makefile: tweak test-everything.

- src/Action.hs
- src/Arbitrary.hs
- src/CreateRandom.hs
- src/Frontend/Page/FileUpload.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Topic.hs
- src/Persistent/Api.hs
- src/Types.hs
- tests/Persistent/ApiSpec.hs
This replaces #211. Some UpdatePersistM class is still a good idea but not to solve the current user tracking.
> Refactoring: package the current user with the prototype upon addDb

- exec/RenderHtml.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Topic.hs
- src/Persistent/Api.hs
(not really showing anything, but the mechanics have made some progress.)
> Page `ViewTopicDelegations`

- src/Action/Implementation.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Path.hs
- tests/Frontend/Page/LoginSpec.hs
> Handle login errors

- src/Arbitrary.hs
- src/Frontend/Page/Login.hs
> Add user details to login page (needed for demo system).

- tests/Frontend/PathSpec.hs
> Test only AulaMain paths.

- aula.cabal
- package.yaml
- src/Config.hs
- src/Frontend.hs
- src/Frontend/Page/Admin.hs
- tests/AulaTests.hs
- tests/Frontend/CoreSpec.hs
> Misc fixes.

- src/Frontend/Page/Topic.hs
Again, this form is the same as as create topic
> Style edit topic page

- src/Arbitrary.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Delegation.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- tests/Frontend/CoreSpec.hs
`Main` path type is used in `formAction` and `redirectOf` functions.
> Path in Form Page class

- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Comment.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Path.hs
- src/Lucid/Missing.hs
- src/Types.hs
- tests/Frontend/CoreSpec.hs
* Styling of comment voting buttons has been a bit broken since now there
is a form element and a button element.
* Handlers for comment replies.
* Pass along the necessary data to vote on comments and replies.
> Support reply and vote buttons

- exec/RenderHtml.hs
- src/Arbitrary.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/LifeCycle.hs
- src/Persistent/Api.hs
- src/Persistent/Idiom.hs
- src/Types.hs
- tests/Frontend/CoreSpec.hs
- add Timestamps to phases that can time out
- add termination phase end Timestamp to ProtoTopic
- phase-switch pattern for html rendering in Page.Idea, Page.Topic
> Termination timestamps for phases.

- src/Frontend.hs
> Refactor the routing table [closes #302]

- Makefile
- aula.cabal
- package.yaml
- src/Action.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Topic.hs
- tests/AulaTests/Stories.hs
- tests/AulaTests/Stories/DSL.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
- tests/AulaTests/Stories/Tests.hs
- tests/AulaTests/StoriesSpec.hs
First test story with an Action interpreter. Testing of pre- and post-conditions are about to come.
> Test stories

- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Prelude.hs
- src/Types.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
The `FormPageHandler` helps testing, in this way the implementation for Actions won't diverge in the Action interpreter for the test DSL, in the case of form pages.
> Add FormPageHandler type.

- src/Frontend/Page/User.hs
not very exciting, but we were asked to fix that this week.  so, there!  (-:
> User settings form redirects to itself.

- src/Frontend/Core.hs
- src/Frontend/Page/Comment.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Path.hs
- static/js/custom.js
- reload on clicks and jump to the right place on the page.
- provide for some minimum type safety.
- fix UI issue.
> Refine js click handlers.

- aula.cabal
- exec/RenderHtml.hs
- package.yaml
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Testing.hs
- static/js/custom.js
- tests/Frontend/PathSpec.hs
> improvements to the RenderHtml process

- src/Arbitrary.hs
- src/Data/UriPath.hs
- src/EventLog.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/Overview.hs
- src/Persistent/Pure.hs
- src/Types.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
- tests/Frontend/CoreSpec.hs
- tests/Frontend/Page/FileUploadSpec.hs
Fixes: https://github.com/liqd/aula/issues/315
> Rename from to un in types

- exec/RenderHtml.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Fragment/Category.hs
- src/Frontend/Fragment/Comment.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Lucid/Missing.hs
- src/Types.hs
- static/js/custom.js
- Includes some cleanup effort in `Frontend.Core`.  First 4 commits do not contain any actual change in functionality.  Just moving stuff around.
> Sorting idea lists

- src/Arbitrary.hs
- src/Frontend/Page/User.hs
- "profil bearbeiten" is a button, not a menu item
- it shows on all tabs
- delegation buttons do not show for own profile
> Tweak profile buttons.

- src/Action.hs
- src/Frontend/Testing.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
(the branch name indicates that my plans changed throughout the making of this PR.  :-)
> Force phase transition through all phases (also jury -> voting)

- src/Action.hs
- src/Action/Smtp.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/User.hs
- src/Frontend/Testing.hs
- src/Persistent/Idiom.hs
- src/Persistent/Pure.hs
- src/Types.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
- tests/Persistent/ApiSpec.hs
> Do not show deleted users.

- src/Frontend/Page/Admin.hs
- tests/Frontend/CoreSpec.hs
Fixes #197.
(Still needs design, but I'll add the resp. links to the pad.)
> UI for admin's user edit, create.

- src/Types.hs
@localgrr this is for you!  (-:  (I'll explain off-line)
> Wrap markdown strings into div elems with resp. class.

- src/Action.hs
- src/Action/Dummy.hs
- src/Action/Implementation.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Testing.hs
- tests/FrontendSpec.hs
* Machinery to render status messages for the user
* One message on saving quorums
* `pageFrame` uses the `Frame` type as a simplification.
> Simple status messages

- src/Frontend/Page/User.hs
I'll do this to resolve #425, which I accidentally closed just now.  It's trivial enough so I'll just merge it myself.
> Status message for user settings.

- src/Data/UriPath.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Path.hs
changes suggested by @np's review.
> Paths & Queries (Errata)

- Makefile
- src/EventLog.hs
- src/Frontend.hs
- src/Frontend/Filter.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Types.hs
Produce string representations of aula types for the UI in a more uniform way.
> Class HasUILabel

- src/Arbitrary.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/LifeCycle.hs
- src/Persistent/Idiom.hs
- src/Types.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
> Apply quorum limit in topic creation

- src/Action.hs
- src/Frontend.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Prelude.hs
- src/Logger/EventLog.hs
- tests/AulaTests.hs
Related: #216 (not sure we should close that yet)
Missing:
```haskell
| EventLogTopicNewPhase         topic Phase Phase
| EventLogIdeaNewTopic          idea (Maybe topic) (Maybe topic)
```
> Throw event log events

- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
I don't have a strong opinion here, but this rules out a bug that was expensive to fix (see https://github.com/liqd/aula/pull/471/commits/e45d958af4f5e4f72a0e75e09c48269237bbfaae).
> Make active tab/menu selection more type safe.

- src/LifeCycle.hs
> Edit idea only in wild and refinement phase.

- src/Frontend/Page/Topic.hs
- src/Persistent/Idiom.hs
- tests/Frontend/CoreSpec.hs
> Render wild ideas on the Create/Edit Topic page.

- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Fragment/VotesBar.hs
- src/Frontend/Page/Idea.hs
> Idea lists voting phase

- src/Frontend/Core.hs
I havent tested it on a phone though
> add mobile meta tag

- src/LifeCycle.hs
- src/Persistent/Idiom.hs
> Refactor freeze

- src/Action.hs
- src/Action/Smtp.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Fragment/Note.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- tests/Frontend/CoreSpec.hs
> Report User

- src/Arbitrary.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/User.hs
- src/LifeCycle.hs
> Moderator can edit user profiles.

- src/Frontend/Fragment/Note.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/User.hs
> Optional explanatory text for Note form.

- src/Config.hs
- src/Frontend/Page/Topic.hs
> Phase timeout info on view topic page.

- src/Frontend/Fragment/Comment.hs
- src/Frontend/Fragment/VotesBar.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/LifeCycle.hs
> Simplify caps computation.

- Makefile
- src/Action.hs
- src/Arbitrary.hs
- src/Backend.hs
- src/DemoData.hs
- src/Frontend.hs
- src/Frontend/Filter.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- src/Persistent/Idiom.hs
- src/Types.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
- tests/Frontend/CoreSpec.hs
> Voting logic

- src/Frontend/Page/Idea.hs
> Change wording of create topic button

- exec/RenderHtml.hs
- src/Access.hs
- src/Action.hs
- src/Arbitrary.hs
- src/Backend.hs
- src/DemoData.hs
- src/Frontend.hs
- src/Frontend/Fragment/VotesBar.hs
- src/Frontend/Page/Delegation.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- src/Logger/EventLog.hs
- src/Persistent/Api.hs
- src/Persistent/Idiom.hs
- src/Persistent/Implementation/AcidState.hs
- src/Persistent/Pure.hs
- src/Types.hs
- tests/DelegationSpec.hs
- tests/Frontend/CoreSpec.hs
> Delegation

- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Path.hs
- tests/Frontend/Page/LoginSpec.hs
After login it redirect to the user settings page form the spaces and the delegations pages.
> Force user to change initial password.

- src/Arbitrary.hs
- src/Frontend/Constant.hs
- src/Frontend/Validation.hs
- tests/Frontend/Page/LoginSpec.hs
> Length constants for username and password checking.

- src/DemoData.hs
- src/Frontend/Constant.hs
- src/Frontend/Page/Login.hs
> Constant passwords in demo data.

- src/Frontend/Page/Topic.hs
- tests/Frontend/CoreSpec.hs
- tests/Test/QuickCheck/Missing.hs
> Check unique topic titles.

- Makefile
- exec/RenderHtml.hs
- src/Action.hs
- src/Arbitrary.hs
- src/Backend.hs
- src/DemoData.hs
- src/Frontend/Page/Delegation.hs
- src/Persistent/Idiom.hs
- src/Persistent/Pure.hs
- src/Types.hs
- static/d3-aula.css
- static/d3-aula.js
Smoothen the delegation network handler and page, and get everything ready for hacking d3js.
> Towards delegation network browsing.

- src/Access.hs
- src/Frontend/Page/Overview.hs
> Moderators can create ideas.

- src/Frontend/Core.hs
- src/Frontend/Fragment/Comment.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Idea.hs
- src/Lucid/Missing.hs
- static/js/custom.js
> Refactor js:simplePost and hs:postButtonConfirm_.

- src/Action/Smtp.hs
- src/Frontend/Filter.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/User.hs
- src/Logger/EventLog.hs
- src/Types.hs
- tests/Persistent/ApiSpec.hs
> Separate showIdeaSpace to uilabel and code functions.

- src/Access.hs
- src/Action.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/User.hs
- tests/Frontend/CoreSpec.hs
> Cancel button on edit user profile page

- src/Access.hs
- src/Action.hs
- src/Arbitrary.hs
- src/Data/Delegation.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Fragment/DelegationTab.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- src/Logger/EventLog.hs
- src/Persistent/Api.hs
- src/Persistent/Idiom.hs
- src/Persistent/Pure.hs
related: #652, #651, #682
user profile has a list of buttons now, one for each class and one for school, all of them toggle.
> Delegation in user profile

- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Fragment/DelegationTab.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- src/Persistent/Idiom.hs
> User profile delegation tab

- .gitignore
- Makefile
- src/Frontend/Page/User.hs
- tests/Frontend/CoreSpec.hs
> Validate image on upload

- src/Action.hs
- tests/AulaTests/Stories/DSL.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
- tests/AulaTests/Stories/Tests.hs
- tests/AulaTests/StoriesSpec.hs
> Fix jury phase forwards

- src/Action.hs
- src/Data/Delegation.hs
- src/Data/DoubleMap.hs
- src/Data/PasswordTokens.hs
- src/Persistent/Pure.hs
> Fix withdraw delegation

- src/Frontend/Fragment/DelegationTab.hs
> Link profile page to delegation views.

- src/Action.hs
> Send email on password reset by admin.

- exec/RenderHtml.hs
- src/Action.hs
- src/Action/Implementation.hs
- src/DemoData.hs
- src/Frontend/Constant.hs
- src/Frontend/Page/User.hs
> User upload page styling

- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
> Add isResponsive flag to Page class.

- src/Action.hs
- src/Config.hs
- src/DemoData.hs
- src/Persistent/Idiom.hs
- src/Persistent/Pure.hs
- src/Types.hs
> Delegating likes

- src/Frontend/Page/Delegation.hs
> Display scope on vote delegation page.

- src/Action.hs
- src/Arbitrary.hs
- src/Data/Delegation.hs
- src/Frontend/Page/Delegation.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Topic.hs
- src/Persistent/Pure.hs
> Revoke delegations on idea topic pages.

- src/Frontend/Page/Admin.hs
- src/Frontend/Validation.hs
> Fix: render the high level validation error message.

- src/Frontend/Page/Delegation.hs
- static/d3-aula.js
> Delegation network, again.

- src/Access.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
> Use right CanDelegate* cap.

- src/DemoData.hs
(which is not clipped for performance reasons).
> Fix: use fish avatars even for demo data

- static/d3-aula.js
One NTH feature, one issue fix.
> Make node sizes more evenly distributed between min and max.

- src/Access.hs
- src/Frontend/Core.hs
- src/Frontend/Page/User.hs
> Delegation capabilities

- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Delegation.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- src/Types/Core.hs
The delegation buttons on profile should work differently if the user opens his/her own profile.
> Delegations on user profile

- Makefile
- docker/hide-crypto-packages.sh
- docker/run.sh
- src/Frontend/Page/User.hs
> User cannot report himself

- .travis.yml
- .travis/docker-build.sh
- .travis/docker-link-stack-workdir.sh
- Makefile
- README.md
- aula.cabal
- docker/hide-crypto-packages.sh
- docker/make-seito.sh
- docker/run.sh
- docs/docker-howto.md
- docs/software-stack.md
- package.yaml
- src/Action.hs
- src/Action/Implementation.hs
- src/Config.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- stack.yaml
- tests/AulaTests.hs
this eliminates the dependency on a thentos git repo being locally installed.
> Get thentos from hackage

- src/Access.hs
- src/Frontend/Core.hs
- src/Frontend/Fragment/DelegationTab.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Page/Delegation.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Types/Util.hs
> Add some "nothing here" when lists are empty (issue #823)

- src/Frontend/Core.hs
> Rename idea space link in frame.

- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- src/Persistent/Pure.hs
- src/Types/Core.hs
- src/Types/Instances/Optics.hs
- src/Types/Instances/SOP.hs
Fixes #870.  Also, lots of refactoring.
> Extra info for delegation buttons

- src/Frontend/Core.hs
- src/Frontend/Fragment/Comment.hs
- src/Frontend/Fragment/DelegationTab.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Delegation.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
Fixes #819.
(hope i didn't forget anything.)
> Img alt texts

- exec/I18N.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/ResetPassword.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Validation.hs
- src/Lucid/I18N.hs
- tests/DelegationSpec.hs
- tests/Frontend/CoreSpec.hs
> Tweak validations

- src/Frontend/Fragment/PhaseTime.hs
> German time stamps on UI.

- HLint.hs
- src/Frontend/Page/User.hs
- src/Types/Util.hs
> Do not render inappropriate tabs on user profile page.

- src/Action.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Fragment/VotesBar.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Path.hs
- src/Persistent/Api.hs
- src/Persistent/Idiom.hs
- src/Persistent/Pure.hs
- src/Types/Core.hs
- src/Types/Instances/SOP.hs
- src/Types/Instances/SafeCopy.hs
- src/Types/Util.hs
- tests/AulaTests/Stories/Interpreter/Action.hs
> Revoke like

- src/Action.hs
> Unvote for delegatees

- .travis.yml
- .travis/docker-build.sh
- Makefile
- aula.cabal
- docker/make-seito.sh
- docker/run.sh
- docker/selenium.sh
- package.yaml
- tests/AulaTests.hs
- tests/SeleniumSpec.hs
- script for running the docker selenium executable.
- trivial test case (everything else can come later).
> selenium testing

- aula.cabal
- package.yaml
- src/Action/Implementation.hs
- src/Arbitrary.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
- src/Logger/EventLog.hs
- src/Types/Core.hs
- src/Types/Prelude.hs
- tests/Frontend/Page/AdminSpec.hs
> Zip csv files before download.

- src/Arbitrary.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Validation.hs
- src/Persistent/Pure.hs
- src/Types/Core.hs
> Lowercase login names

- aula.cabal
- exec/InitState.hs
- package.yaml
- src/DemoData.hs
- src/Frontend.hs
> Bootstrap aula env

- src/Frontend/Page/Admin.hs
> Hack: Hide wrongly rendered first post button.

- src/Frontend/Core.hs
- src/Frontend/Fragment/VotesBar.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/User.hs
> Wording changes

- aula.cabal
- package.yaml
- src/Frontend.hs
- stack.yaml
Fixes #932.
(well, not really.  clarifies that there wasn't anything to fix.)
> Bump thentos-cookie-session.

- src/Arbitrary.hs
- src/Config.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Middleware.hs
- src/Frontend/Testing.hs
- tests/AulaTests.hs
- tests/FrontendSpec.hs
> 404 styling and encoding.

- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Middleware.hs
- tests/Frontend/CoreSpec.hs
> Render 5xx server errors.

- src/Config.hs
- src/Daemon.hs
- src/Frontend.hs
- src/Types/Prelude.hs
> Cleanup daemon

- src/Action/Smtp.hs
- src/Config.hs
- src/DemoData.hs
- make default recipient in config mandatory
- send better test email on server start.
> smtp config and test email.

- src/Frontend/Page/ResetPassword.hs
> Turn off CSRF token for passwordResetViaEmail.

- aula.cabal
- src/Action.hs
- src/Action/Implementation.hs
- src/Action/Smtp.hs
- src/Config.hs
- src/Daemon.hs
- src/Logger.hs
- src/Persistent/Implementation/AcidState.hs
- src/Persistent/Pure.hs
- src/Types.hs
- src/Types/Log.hs
- tests/AllModulesSpec.hs
- tests/AulaTests.hs
> Log action exceptions

- src/Frontend/Core.hs
> Fix: show menu on mobile.

- .travis/docker-build.sh
- aula.cabal
- exec/Aula.hs
- package.yaml
- src/Action.hs
- src/Action/Smtp.hs
- src/Frontend/Constant.hs
- src/Frontend/Core.hs
- src/Frontend/Fragment/Comment.hs
- src/Frontend/Fragment/DelegationTab.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Middleware.hs
- src/Frontend/Page/Admin.hs
- tests/AulaTests/Stories/Interpreter/WebDriver.hs
- tests/Frontend/Page/FileUploadSpec.hs
- text encoding issues.
- if csv files contain empty lines, those should not trigger bogus user creation.
- ~~tweak avatar image browser caching.~~
- tweak avatar image size selection.
- devops niceties.
> csv upload tweaks etc.

- src/Frontend/Page/Idea.hs
> Fix: moderator permissions on idea comments.

- src/Data/Delegation.hs
- src/Frontend/Page/User.hs
> Flip delegation tab names on the user profile page.

- aula.cabal
- src/Frontend/Validation.hs
- src/Persistent/Pure.hs
- src/Types/Core.hs
- tests/Persistent/PureSpec.hs
- tests/Test/QuickCheck/Missing.hs
> Filter out invalid characters at user creation

- src/Arbitrary.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Validation.hs
- src/Types/Core.hs
- tests/Frontend/CoreSpec.hs
> class names with dashes

- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Filter.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Topic.hs
- tests/AulaTests.hs
This done and now ready for review and merge #1003 .
> Add support to search for ideas

- src/Frontend/Validation.hs
- src/Types/Core.hs
> Do not write standard "class" before group names

- aula.cabal
- src/Frontend/Page/Admin.hs
- src/Types/Instances/SafeCopy.hs
- src/Types/Old.hs
> Migration 1

- src/Frontend/Page/Admin.hs
also, style user admin form a little.
> Fix: eliminate nested html forms (it is illegal *and* did not work)

- aula.cabal
- exec/ResetAllPasswords.hs
- package.yaml
- src/Frontend/Page/Admin.hs
this is a bit of a hack, but it is isolated in a separate executable.  the source code is the documentation!  (-:
> Bulk reset passwords
