- .travis.yml
- README
The build on [travis](https://travis-ci.org/liqd/aula) now tries to install aula. There is a build state indicator in the README file.
NOTE: Somehow the travis cache is not working as expected, but until the build does not reach critical timelimit or number of pushes/hour. We can live with it. (E.g. The resolution could be done via docker image, I've it done before)
> Simple Travis Build

- .travis.yml
- travis/docker-build.sh
- travis/docker-list-sandbox-packages.sh
Steps what the travis build does at testing:
* Pulls out the `fisx/aula` docker image, which has thentos and aula dependencies installed in a cabal sandbox `/liqd/thentos/.cabal-sandbox`. 
* Show the versions of installed packages for debug purposes
* Runs the normal cabal test suite that can be found in `travis/docker-build.sh`
> Dockerize travis build.

- src/Api/Persistent.hs
- src/Frontend.hs
- src/Frontend/Html.hs
- src/Types.hs
Additions to Api.Persistent:
* getDb
* addDb
* modifyDb
* getUsers
* addUser
* findUserByLogin
* loginUser
* dbUsers
* dbCurrentUser
New endpoints in Frontend:
* GET users/create_random
* GET users
* GET login/:login
Frontend.Html:
* Add PageShow which enables to write dev pages using the underlying Show instance.
Types:
* Add lenses for direct access to the meta data of users and ideas.
> Extend the DB with users and current user

- Makefile
- aula.cabal
- exec/RenderHtml.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Html.hs
- src/Frontend/Page/CreateIdea.hs
- src/Frontend/Page/HomePageWithLoginPrompt.hs
- src/Frontend/Page/Topics.hs
- src/Frontend/Pages.hs
- tests/Frontend/HtmlSpec.hs
- tests/Frontend/PageSpec.hs
* Different frame for the login page
* Login handler which redirectes to ideas page after login (login always succeeds)
* Rename `Frontend.Topic` to `Frontend.Page.Topics`
* Create `Frontend.Pages` module
* Add `make aula-server-run`
* More compact form in `Frontend.Page.CreateIdea`
* Add `Page` typeclass
* Add `redirectFormHandler`
> Login Page

- .travis.yml
- HLint.hs
- Makefile
- travis/docker-hlint.sh
HLint checks are added to travis build. It won't break the build for the time being, until we figure out the common rules. Please contribute to `src/HLint.hs` or comment on this thread.
> Add hlint to travis build.

- Makefile
- README.md
- aula.cabal
- exec/RenderHtml.hs
- src/Config.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Types.hs
- static/samples
- tests/FrontendSpec.hs
I just checked: on my laptop, I can set up sensei to watch the repo and on changes in src/Frontend/Page/*.hs, refresh of all html will take <3s.
The only problem is that sensei can't un-watch files.  See https://github.com/hspec/sensei/pull/28 for a discussion what needs to be done there.
> Use sensei to drive exec/RenderHtml.

- README.md
I've tested the instructions for docker. They work fine. Here are a few minor fixes.
> README.md: Fix 'Getting started (with docker)' section

- aula.cabal
- package.yaml
(@Mikolaj, you edited `aula.cabal` directly a few PRs back.  That works and can always be fixed later by someone else, as in this PR, but the better thing to do is edit `package.yaml` and call https://github.com/sol/hpack/ to generate the cabal file.)
> Re-align hpack's package.yaml file with aula.cabal.

- docs/page-creator-howto.md
I think, the instructions for pages under `samples/` are now fairly complete (whether accurate and up-to-date is another matter; please fix and update).
> Improve page-creator-howto

- src/Types.hs
This is actually a re-export from Text.Digestive.Util.
> Add readMaybe to our "Prelude"

- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Path.hs
- Export `redirect` from `Frontend.Core`.
- Add instance for `ToHtml ()`.
- Add path `Top -> "/"`.
- Add route `/` redirecting to `/space`.
> Redirect from `/` to `/space`.

- exec/RenderHtml.hs
- src/Arbitrary.hs
(@Mikolaj you've reviewed #193, and we both forgot: wasn't there a problem with `unsafePerformaIO` inlining before?)
> Fixes for #193

- src/Frontend/Path.hs
Very small PR, but very helpful!
> Make broken links actually break, not mysteriously re-direct to /spaces.

- aula.cabal
- exec/RenderHtml.hs
- src/Action.hs
- src/Action/Dummy.hs
- src/Action/Implementation.hs
- src/Arbitrary.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Login.hs
- src/Persistent/Api.hs
- tests/Frontend/CoreSpec.hs
- tests/Frontend/Page/LoginSpec.hs
- tests/Frontend/PathSpec.hs
* FormPage.makeForm: the monad now has the ActionM constraint
* ActionUserHandler.login: now takes a User instead of UserLogin
* New module Action.Dummy: a tiny monad stack which errors out most of the time
* The FormPagePayload of the login page is now User, the DB lookup of the
login happens as part of validation
* As we cannot reconstruct the password the corresponding test has been disabled
> Lookup the user upon login as part of form validation

- aula.cabal
- src/Arbitrary.hs
- src/Backend.hs
- src/Frontend.hs
- src/Persistent/Implementation/STM.hs
- src/Types.hs
- tests/BackendSpec.hs
- Add Backend module and export fish sample networks.
- Allow GenArbitrary to run `Gen` actions.
- Make handler types and fish sample network generation more polymorphic.
This is all a bit silly: the new end-point logs in admin implicitly; the returned delegation networks are generated on top of the existing data; testing doesn't really test anything.  But it is self-contained and a good basis to continue from.
> Introduce rest api for delegation network queries.

- src/Action.hs
- src/Action/Dummy.hs
- src/Action/Implementation.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Persistent/Api.hs
- src/Persistent/Implementation/STM.hs
- tests/Frontend/PathSpec.hs
- tests/Persistent/ApiSpec.hs
This introduces exceptions for PersistM in a minimal way.
The next step would be to change the types `ActionExcept` and `PersistExcept` as indicated in the resp. FIXMEs.
> Persist vs. Except

- .gitignore
- exec/RenderHtml.hs
- src/Action.hs
- src/Arbitrary.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Page/Overview.hs
- src/Frontend/Page/Topic.hs
- src/Frontend/Page/User.hs
- src/Frontend/Path.hs
- src/LifeCycle.hs
- src/Types.hs
- tests/AulaTests.hs
- tests/Frontend/PathSpec.hs
Copy of #349.
- Ignore aula.yaml and persistented data.
- Run test suite with in memory acid-state implementation.
- Add some paths tests.
- Add simple user context for idea list related pages.
- Add RenderContext.
- Use composite query in juryIdea.
- Use 'ideaCapabilities' in ListIdeaItem rendering.
> Jury phase pages

- src/Action.hs
- src/Frontend/Page/Overview.hs
- src/Persistent/Pure.hs
- src/Types.hs
* Change: use getSpacesForCurrentUser in viewRooms
* Renaming: The fields to access school classes in Role
are now unified makes the resulting lens useful
(it is a Traversal actually).
* New: Action.getSpacesForCurrentUser
* New: Persistent.Pure.getSpacesForRole
> Restrict spaces to the current user

- src/Data/UriPath.hs
- src/EventLog.hs
- src/Frontend.hs
- src/Frontend/Fragment/IdeaList.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Idea.hs
- src/Frontend/Path.hs
- src/Types.hs
- tests/Frontend/Page/AdminSpec.hs
More exhaustive support for uri queries and hashes in `Data.UriPath`, `Frontend.Path`.
Fixes #31, improves usability of buttons vote/comment/report, and resolves this:
```haskell
-- [Frontend.hs]
:<|> adminEventLogCsv . Just  -- FIXME: with QueryParam, we could melt these two routes into one.
-- this isn't a hard task, but we need to extend 'UriPath' type.
```
> Paths & Queries

- src/Action.hs
- src/DemoData.hs
- src/Frontend/Page/Admin.hs
- src/LifeCycle.hs
- src/Persistent/Pure.hs
- src/Types.hs
- tests/Persistent/ApiSpec.hs
Fixes 2 issues with creating frozen topics:
- see FIXME;
- the leftover time was set to 0 instead of the configured maximum.
> More expressive types for phase timespans.

- Makefile
Introduces the shell syntax `make grep.TODO`.
I use this for my strange emacs setup.
> Add make rule for git-grep.

- src/Action.hs
- src/Frontend.hs
- src/Frontend/Page/Admin.hs
- src/LifeCycle.hs
- tests/Frontend/CoreSpec.hs
Fixes #472, but does more.
Most notably:
- we can now shift back through all phases from result to refinement
- jury statements are not removed any more when switching back to jury phase.  (i think this means that the next edit will trigger another phase shift.  we should think about this some more.)
> Shifting phases

- src/Action.hs
- src/Arbitrary.hs
- src/Data/UriPath.hs
- src/Frontend.hs
- src/Frontend/Core.hs
- src/Frontend/Page/Admin.hs
- src/Frontend/Page/Login.hs
- src/Frontend/Path.hs
- src/Logger/EventLog.hs
- src/Lucid/Missing.hs
- tests/Frontend/CoreSpec.hs
- tests/Frontend/Page/FileUploadSpec.hs
- tests/Frontend/PathSpec.hs
Smart constructors should be introduced for every path we use as to achieve the full type safeness. I would do that in a different PR to minimize the size of the lousy coupled changes.
> Type safety for paths

- src/Frontend/Core.hs
- src/Frontend/Page/Delegation.hs
i hear this is how js people load code these days, and we're only using it for that.
> Allow pages to have extra footer elems rather than page headers.

- src/Frontend/Core.hs
- static/js/custom.js
Fixes #578.
This was surprisingly simple.  We now don't reload the page after a fixed timeout, but after the response on the POST has been received.
> Unwobble buttons

- src/Frontend/Page/Topic.hs
Fixes: #597 
- On create topic page it points to the list topics page.
- On edit topic page goes back to the topic itself.
> Cancel button on create and edit topic pages.

- .gitattributes
- Makefile
- aula.cabal
- exec/ResizeAvatar.hs
- package.yaml
- src/Data/Avatar.hs
- src/Frontend/Constant.hs
- src/Frontend/Page/User.hs
- src/Types.hs
Fixes #598.  Fixes #436.
* Avatars are scaled up if needed and then clipped to circles.
* Add a new command aula-avatars which helps testing the avatars
for a list of dimensions and files.
* Add avatarDefaultSize and avatarExtraSizes in Frontend.Constant.
* Uploading a new avatar now resizes to all these sizes.
> Scale and circle avatars

- src/Frontend/Core.hs
- src/Frontend/Page/Delegation.hs
- static/d3-aula.js
- static/js/custom.js
Fixes the following unreported issues:
- delegate on user profile doesn't reload properly
- if you delegate to yourself and then close your node's delegatees in the graph, you close the node itself.
- delegate-to page behind topics, ideas: current delegation is rendered correctly (still not fixed: #728).
> Misc fixes.

- src/Persistent/Pure.hs
- src/Types/Instances/JSON.hs
- static/d3-aula.css
- static/d3-aula.js
Fixes #827.  Fixes #825.
The user instructions have changed a bit again:
1. nodes that have hidden edges now look a little transparent so you know you have to click on them.  1. if you click on a node, all direct neighbours are toggled.  you have to keep clicking if you want to see more.
1. if you search for users, you only see matching nodes, but you can see by their transparency which ones to click on.
1. if you click on a node, all neighbors are made visible if and only if there is at least one invisible neighbor.  (before a click changed the visibility of all neighbors to the opposite of an arbitrary neighbor.)
i tried to unfold neighbors during the search, but it didn't work in the time box i had.
> Delegation network, again.

- src/Frontend/Core.hs
- src/Frontend/Fragment/ContextMenu.hs
I have ... menus a title so they are accessible now. I didnt change the text to "Optionen" I think this makes it hard to read 
How should I proceed ?
> Gave ... menus a title #820

- .travis/docker-build.sh
I'm basing this change on my half-baked bash theories, but I think this was a bug.  It may never have been triggered so far, though.
> Fix docker build script.

- README.md
I was giving `aula` a test run and ran into empty submodules. 
This solved it.
> add `--recursive` to grab submodule code

- src/Frontend.hs
- src/Frontend/Middleware.hs
- src/Persistent/Idiom.hs
```
$ curl -v http://localhost:8080/login > /dev/null 
[...]
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Date: Mon, 22 Aug 2016 09:30:45 GMT
* Server Warp/3.2.7 is not blacklisted
< Server: Warp/3.2.7
< Cache-Control: no-cache, no-store, must-revalidate
< Expires: 0
< Set-Cookie: aula=1839822807284392500000; Path=/
< Content-Type: text/html;charset=utf-8
[...]
$ curl -v http://localhost:8080/static/d3-aula.css > /dev/null 
[...]
< HTTP/1.1 200 OK
< Last-Modified: Wed, 10 Aug 2016 12:22:11 GMT
< Content-Length: 618
< Accept-Ranges: bytes
< Date: Mon, 22 Aug 2016 09:30:48 GMT
* Server Warp/3.2.7 is not blacklisted
< Server: Warp/3.2.7
< Cache-Control: public
< Content-Type: text/css
< last-modified: Wed, 10 Aug 2016 12:22:11 GMT
[...]
```
> Cache control: cache static content

- Makefile
- aula.cabal
- src/Action.hs
- src/Arbitrary.hs
- src/Frontend/Constant.hs
- src/Logger/EventLog.hs
- tests/ActionSpec.hs
Fixes #1030.
Event log download was choking on ideas from deleted class rooms.  Now the event log contains a note "GELÖSCHT" ("DELETED") in those places.
Missing:
> Event log with deleted items.
